// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// AbSystemAdminDao is the manager for logic model data accessing and custom defined data operations functions management.
type AbSystemAdminDao struct {
	Table   string               // Table is the underlying table name of the DAO.
	Group   string               // Group is the database configuration group name of current DAO.
	Columns AbSystemAdminColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// AbSystemAdminColumns defines and stores column names for table ab_system_admin.
type AbSystemAdminColumns struct {
	Id         string //
	AuthIds    string // 角色权限ID
	HeadImg    string // 头像
	Username   string // 用户登录名
	Password   string // 用户登录密码
	Phone      string // 联系手机号
	Remark     string // 备注说明
	LoginNum   string // 登录次数
	Sort       string // 排序
	Status     string // 状态(0:禁用,1:启用,)
	CreateTime string // 创建时间
	UpdateTime string // 更新时间
	DeleteTime string // 删除时间
}

//  abSystemAdminColumns holds the columns for table ab_system_admin.
var abSystemAdminColumns = AbSystemAdminColumns{
	Id:         "id",
	AuthIds:    "auth_ids",
	HeadImg:    "head_img",
	Username:   "username",
	Password:   "password",
	Phone:      "phone",
	Remark:     "remark",
	LoginNum:   "login_num",
	Sort:       "sort",
	Status:     "status",
	CreateTime: "create_time",
	UpdateTime: "update_time",
	DeleteTime: "delete_time",
}

// NewAbSystemAdminDao creates and returns a new DAO object for table data access.
func NewAbSystemAdminDao() *AbSystemAdminDao {
	return &AbSystemAdminDao{
		Group:   "default",
		Table:   "ab_system_admin",
		Columns: abSystemAdminColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AbSystemAdminDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AbSystemAdminDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AbSystemAdminDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
