// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// AbSystemAuthNodeDao is the manager for logic model data accessing and custom defined data operations functions management.
type AbSystemAuthNodeDao struct {
	Table   string                  // Table is the underlying table name of the DAO.
	Group   string                  // Group is the database configuration group name of current DAO.
	Columns AbSystemAuthNodeColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// AbSystemAuthNodeColumns defines and stores column names for table ab_system_auth_node.
type AbSystemAuthNodeColumns struct {
	Id     string //
	AuthId string // 角色ID
	NodeId string // 节点ID
}

//  abSystemAuthNodeColumns holds the columns for table ab_system_auth_node.
var abSystemAuthNodeColumns = AbSystemAuthNodeColumns{
	Id:     "id",
	AuthId: "auth_id",
	NodeId: "node_id",
}

// NewAbSystemAuthNodeDao creates and returns a new DAO object for table data access.
func NewAbSystemAuthNodeDao() *AbSystemAuthNodeDao {
	return &AbSystemAuthNodeDao{
		Group:   "default",
		Table:   "ab_system_auth_node",
		Columns: abSystemAuthNodeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AbSystemAuthNodeDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AbSystemAuthNodeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AbSystemAuthNodeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
