// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// AbSystemAuthDao is the manager for logic model data accessing and custom defined data operations functions management.
type AbSystemAuthDao struct {
	Table   string              // Table is the underlying table name of the DAO.
	Group   string              // Group is the database configuration group name of current DAO.
	Columns AbSystemAuthColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// AbSystemAuthColumns defines and stores column names for table ab_system_auth.
type AbSystemAuthColumns struct {
	Id         string //
	Title      string // 权限名称
	Sort       string // 排序
	Status     string // 状态(1:禁用,2:启用)
	Remark     string // 备注说明
	CreateTime string // 创建时间
	UpdateTime string // 更新时间
	DeleteTime string // 删除时间
}

//  abSystemAuthColumns holds the columns for table ab_system_auth.
var abSystemAuthColumns = AbSystemAuthColumns{
	Id:         "id",
	Title:      "title",
	Sort:       "sort",
	Status:     "status",
	Remark:     "remark",
	CreateTime: "create_time",
	UpdateTime: "update_time",
	DeleteTime: "delete_time",
}

// NewAbSystemAuthDao creates and returns a new DAO object for table data access.
func NewAbSystemAuthDao() *AbSystemAuthDao {
	return &AbSystemAuthDao{
		Group:   "default",
		Table:   "ab_system_auth",
		Columns: abSystemAuthColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AbSystemAuthDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AbSystemAuthDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AbSystemAuthDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
