// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// AbSystemConfigDao is the manager for logic model data accessing and custom defined data operations functions management.
type AbSystemConfigDao struct {
	Table   string                // Table is the underlying table name of the DAO.
	Group   string                // Group is the database configuration group name of current DAO.
	Columns AbSystemConfigColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// AbSystemConfigColumns defines and stores column names for table ab_system_config.
type AbSystemConfigColumns struct {
	Id         string //
	Name       string // 变量名
	Group      string // 分组
	Value      string // 变量值
	Remark     string // 备注信息
	Sort       string //
	CreateTime string // 创建时间
	UpdateTime string // 更新时间
}

//  abSystemConfigColumns holds the columns for table ab_system_config.
var abSystemConfigColumns = AbSystemConfigColumns{
	Id:         "id",
	Name:       "name",
	Group:      "group",
	Value:      "value",
	Remark:     "remark",
	Sort:       "sort",
	CreateTime: "create_time",
	UpdateTime: "update_time",
}

// NewAbSystemConfigDao creates and returns a new DAO object for table data access.
func NewAbSystemConfigDao() *AbSystemConfigDao {
	return &AbSystemConfigDao{
		Group:   "default",
		Table:   "ab_system_config",
		Columns: abSystemConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AbSystemConfigDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AbSystemConfigDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AbSystemConfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
