// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// AuthoritiesDao is the manager for logic model data accessing and custom defined data operations functions management.
type AuthoritiesDao struct {
	Table   string             // Table is the underlying table name of the DAO.
	Group   string             // Group is the database configuration group name of current DAO.
	Columns AuthoritiesColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// AuthoritiesColumns defines and stores column names for table authorities.
type AuthoritiesColumns struct {
	AuthorityId   string // 角色ID
	AuthorityName string // 角色名
	ParentId      string // 父角色ID
	CreateAt      string // 创建时间
	UpdateAt      string // 更新时间
	DeleteAt      string // 删除时间
}

//  authoritiesColumns holds the columns for table authorities.
var authoritiesColumns = AuthoritiesColumns{
	AuthorityId:   "authority_id",
	AuthorityName: "authority_name",
	ParentId:      "parent_id",
	CreateAt:      "create_at",
	UpdateAt:      "update_at",
	DeleteAt:      "delete_at",
}

// NewAuthoritiesDao creates and returns a new DAO object for table data access.
func NewAuthoritiesDao() *AuthoritiesDao {
	return &AuthoritiesDao{
		Group:   "default",
		Table:   "authorities",
		Columns: authoritiesColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AuthoritiesDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AuthoritiesDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AuthoritiesDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
