// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
)

// apisDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type apisDao struct {
	*internal.ApisDao
}

var (
	// Apis is globally public accessible object for table apis operations.
	Apis = apisDao{
		internal.NewApisDao(),
	}
)

// Fill with you ideas below.
