// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
)

// authorityResourcesDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type authorityResourcesDao struct {
	*internal.AuthorityResourcesDao
}

var (
	// AuthorityResources is globally public accessible object for table authority_resources operations.
	AuthorityResources = authorityResourcesDao{
		internal.NewAuthorityResourcesDao(),
	}
)

// Fill with you ideas below.
