// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
)

// breakpointFilesDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type breakpointFilesDao struct {
	*internal.BreakpointFilesDao
}

var (
	// BreakpointFiles is globally public accessible object for table breakpoint_files operations.
	BreakpointFiles = breakpointFilesDao{
		internal.NewBreakpointFilesDao(),
	}
)

// Fill with you ideas below.
