// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
)

// jwtsDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type jwtsDao struct {
	*internal.JwtsDao
}

var (
	// Jwts is globally public accessible object for table jwts operations.
	Jwts = jwtsDao{
		internal.NewJwtsDao(),
	}
)

// Fill with you ideas below.
