// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
)

// loginLogDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type loginLogDao struct {
	*internal.LoginLogDao
}

var (
	// LoginLog is globally public accessible object for table login_log operations.
	LoginLog = loginLogDao{
		internal.NewLoginLogDao(),
	}
)

// Fill with you ideas below.
