// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
)

// menusDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type menusDao struct {
	*internal.MenusDao
}

var (
	// Menus is globally public accessible object for table menus operations.
	Menus = menusDao{
		internal.NewMenusDao(),
	}
)

// Fill with you ideas below.
