// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
)

// onlineUserDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type onlineUserDao struct {
	*internal.OnlineUserDao
}

var (
	// OnlineUser is globally public accessible object for table online_user operations.
	OnlineUser = onlineUserDao{
		internal.NewOnlineUserDao(),
	}
)

// Fill with you ideas below.
