// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
)

// parametersDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type parametersDao struct {
	*internal.ParametersDao
}

var (
	// Parameters is globally public accessible object for table parameters operations.
	Parameters = parametersDao{
		internal.NewParametersDao(),
	}
)

// Fill with you ideas below.
