// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
)

// roleResourcesDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type roleResourcesDao struct {
	*internal.RoleResourcesDao
}

var (
	// RoleResources is globally public accessible object for table role_resources operations.
	RoleResources = roleResourcesDao{
		internal.NewRoleResourcesDao(),
	}
)

// Fill with you ideas below.
